### ISSUE TITLE
pip installation

### ISSUE THREAD

**Issue by jrherr** [coelias/Pynteractive#1]
Pip installation retrieves no package:

```
$ pip install pynteractive
Collecting pynteractive
  Could not find a version that satisfies the requirement pynteractive (from versions: )
  No matching distribution found for pynteractive
```

Has this package been submitted for distribution?

(Update) - git cloning and installing worked for me after I tried pip.

**Comment by coelias** [comment]
Yes there was an error in the setup.py so the project wasn't properly uploaded

Thanks Josh

**Comment by jrherr** [comment]
Works great!  Thanks for the fix.
